language: python
python:
  - "3.6.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  
# command to run tests
script:
  - py.test --cov

after_success:
- coveralls
